version: "3.7"

services:
  react-portfolio:
    environment:
      VIRTUAL_HOST: mauriciosalzar.dev, www.mauriciosalzar.dev
      LETSENCRYPT_HOST: mauriciosalzar.dev, www.mauriciosalzar.dev
      LETSENCRYPT_EMAIL: maurisa2004@gmail.com
      VIRTUAL_PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
      # - 80:3500
    container_name: react-portfolio
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    external:
      name: nginx-proxy
